<a href="https://colab.research.google.com/github/NeuralDataMind/PyTorch/blob/main/Activation_func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
# softmax activation

logits = torch.tensor([[2.3, 0.4, 1.1], [0.1, 2.2, 0.6], [0.3, 0.3, 3.0]])
softmax_prob = torch.softmax(logits, dim = 1)
print(softmax_prob)

tensor([[0.6893, 0.1031, 0.2076],
        [0.0925, 0.7551, 0.1524],
        [0.0592, 0.0592, 0.8815]])


In [ ]:
# LeakyReLU

class SimpleNN(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.layer_1 = nn.Linear(input_size, hidden_size)
    self.LeakyReLU = nn.LeakyReLU(negative_slope = 0.01)
    self.layer_2 = nn.Linear(hidden_size, output_size)

  def forward(self, x):
    x = self.layer_1(x)
    x = self.LeakyReLU(x)
    x = self.layer_2(x)
    return x

input_size = 10
hidden_size = 20
output_size = 1

model = SimpleNN(input_size, hidden_size, output_size)

input_data = torch.randn(5, input_size)

output_data = model(input_data)

print(input_data)
print(output_data)

tensor([[ 0.1328,  2.4767, -0.0203, -0.9344, -0.9423, -0.1368,  0.0297,  0.5052,
          0.6273,  0.1548],
        [ 1.3067, -1.9355,  0.2729,  1.5221, -0.2315, -1.6914,  2.0548, -0.9555,
          0.4264,  1.9079],
        [-0.8618, -0.6846,  1.2754, -0.3855, -0.5225, -0.6706, -0.0491, -0.7587,
         -1.5609, -0.9203],
        [-0.2261, -1.1226, -1.2866, -0.0738,  1.1924,  1.4644,  0.4218, -0.7246,
          0.5024,  0.4242],
        [-0.1889, -0.1370, -0.2232, -0.6944, -1.8551, -0.0832, -1.7238,  0.3013,
          0.7268, -0.1147]])
tensor([[-0.2414],
        [-1.0141],
        [-0.0261],
        [-0.3105],
        [-0.2032]], grad_fn=<AddmmBackward0>)


In [ ]:
# relu and selu

class SimpleNN(nn.Module):
  def __init__(self, input_size, hidden_size, output_size):
    super().__init__()
    self.layer_1 = nn.Linear(input_size, hidden_size)
    self.layer_2 = nn.Linear(hidden_size, output_size)

  def forward(self, x):
    x_relu = torch.relu(self.layer_1(x))
    x_selu = torch.selu(self.layer_2(x_relu))
    return x_relu, x_selu

input_size = 10
hidden_size = 20
output_size = 1

model = SimpleNN(input_size, hidden_size, output_size)

input_data = torch.randn(5, input_size)

output_relu, output_selu = model(input_data)
print(input_data)
print(output_relu)
print(output_selu)

tensor([[-0.6512, -0.4503,  0.6739,  0.1371, -0.3391, -2.0289, -1.1695,  0.9588,
          1.4451, -0.5292],
        [ 0.4020, -0.8137, -0.5520, -0.1770, -1.0305, -0.6769, -0.2165, -0.2667,
          1.1718, -0.9392],
        [ 1.1278, -0.4512, -2.7633,  1.3437,  0.3032,  1.8937, -0.3153,  0.5849,
          1.6746, -1.0394],
        [-0.1975,  0.0861, -1.0061,  1.6371, -1.0192,  0.0952, -2.1519, -0.8760,
          0.1510,  0.1212],
        [ 0.9590, -0.6507, -0.1842,  0.1240,  1.4292,  0.3306, -0.9146, -0.2832,
          1.7315, -0.5001]])
tensor([[0.0000, 0.0000, 0.0000, 0.7429, 0.0000, 0.4975, 0.0000, 0.2031, 0.7939,
         0.1883, 0.0000, 0.5556, 0.0729, 0.0920, 0.0512, 0.0000, 0.4023, 0.2363,
         0.0185, 0.1032],
        [0.0000, 0.3773, 0.0000, 0.0000, 0.0000, 0.7052, 0.0000, 0.0000, 0.4979,
         0.5234, 0.0000, 0.2483, 0.2589, 0.0000, 0.3912, 0.0000, 0.4578, 0.6694,
         0.0000, 0.0000],
        [0.0000, 1.1216, 0.0000, 0.0617, 0.0000, 1.5710, 0.0000, 0.0000, 0.161