<a href="https://colab.research.google.com/github/NeuralDataMind/PyTorch/blob/main/Intro_to_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_1 = torch.tensor([1, 2, 3])
print("Our first PyTorch Tensor:", tensor_1)

Our first PyTorch Tensor: tensor([1, 2, 3])


In [3]:
array_1 = np.array([1, 2, 3])

In [5]:
tensor_from_numpy = torch.tensor(array_1)
print("PyTorch Twnsor from numpy arraay:", tensor_from_numpy)

PyTorch Twnsor from numpy arraay: tensor([1, 2, 3])


In [7]:
empty_tensor = torch.empty(3)
print("Empty Tensor:", empty_tensor)

Empty Tensor: tensor([-1.6904e+14,  4.3914e-41,  2.0435e-08])


In [9]:
zero_tensor = torch.zeros(2, 3)
print("Zero Tensor:", zero_tensor)

Zero Tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
ones_tensor = torch.ones(2, 3)
print("Ones Tensor:", ones_tensor)

Ones Tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
arange_tensor = torch.arange(0, 10, 1)
print("Arange Tensor:", arange_tensor)

Arange Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
arange_tensor =torch.arange(start = 0, end = 10, step = 1)
print("Arange Tensor:", arange_tensor)

Arange Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [18]:
random_tensor = torch.randn(3, 3)
print("Random Tensor:", random_tensor)

Random Tensor: tensor([[-0.1518,  0.3522, -1.9880],
        [ 1.0300,  0.3439,  0.2152],
        [ 0.6659, -0.3414, -0.2676]])


In [22]:
random_tensor[0, 0]

tensor(-0.1518)

In [21]:
random_tensor[0, :]

tensor([-0.1518,  0.3522, -1.9880])

In [23]:
random_tensor[:, 0]

tensor([-0.1518,  1.0300,  0.6659])

In [24]:
random_tensor[1, 1].item()

0.34392282366752625

In [26]:
reshaped_tensor = torch.rand(5, 4)
print("Reshaped Tensor", reshaped_tensor)

Reshaped Tensor tensor([[0.8346, 0.9660, 0.8361, 0.7227],
        [0.7480, 0.1472, 0.0390, 0.9677],
        [0.6372, 0.5773, 0.6404, 0.8046],
        [0.5181, 0.6639, 0.2963, 0.0593],
        [0.9073, 0.2331, 0.4745, 0.2583]])


**Reshape and view**

reshape and view both do same thing

In [28]:
new_reshaped_tensor = reshaped_tensor.view(4,5)
print("New Reshaped Tensor:", new_reshaped_tensor)

New Reshaped Tensor: tensor([[0.8346, 0.9660, 0.8361, 0.7227, 0.7480],
        [0.1472, 0.0390, 0.9677, 0.6372, 0.5773],
        [0.6404, 0.8046, 0.5181, 0.6639, 0.2963],
        [0.0593, 0.9073, 0.2331, 0.4745, 0.2583]])


In [30]:
new_reshaped_tensor = reshaped_tensor.view(-1, 2)
print("New Reshaped Tensor:", new_reshaped_tensor)

New Reshaped Tensor: tensor([[0.8346, 0.9660],
        [0.8361, 0.7227],
        [0.7480, 0.1472],
        [0.0390, 0.9677],
        [0.6372, 0.5773],
        [0.6404, 0.8046],
        [0.5181, 0.6639],
        [0.2963, 0.0593],
        [0.9073, 0.2331],
        [0.4745, 0.2583]])


In [32]:
new_reshaped_tensor = reshaped_tensor.view(5, -1)
print("New Reshaped Tensor:", new_reshaped_tensor)

New Reshaped Tensor: tensor([[0.8346, 0.9660, 0.8361, 0.7227],
        [0.7480, 0.1472, 0.0390, 0.9677],
        [0.6372, 0.5773, 0.6404, 0.8046],
        [0.5181, 0.6639, 0.2963, 0.0593],
        [0.9073, 0.2331, 0.4745, 0.2583]])


In [56]:
new_reshaped_tensor = reshaped_tensor.reshape(-1, 2)
print("New Reshaped Tensor:", new_reshaped_tensor)

New Reshaped Tensor: tensor([[0.8346, 0.9660],
        [0.8361, 0.7227],
        [0.7480, 0.1472],
        [0.0390, 0.9677],
        [0.6372, 0.5773],
        [0.6404, 0.8046],
        [0.5181, 0.6639],
        [0.2963, 0.0593],
        [0.9073, 0.2331],
        [0.4745, 0.2583]])


**Tensor Operations**

In [36]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

result_add_1 = torch.add(tensor_a, tensor_b)
result_add_2 = tensor_a + tensor_b

print("func :",result_add_1)
print("operation :", result_add_2)

func : tensor([5, 7, 9])
operation : tensor([5, 7, 9])


In [40]:
print(tensor_a.add(tensor_b)) # But it doesnot effect the value of tensor_a
print(tensor_a)

tensor([5, 7, 9])
tensor([1, 2, 3])


In [41]:
print(tensor_a.add_(tensor_b)) # It will effect the value of tensor_a
print(tensor_a)

tensor([5, 7, 9])
tensor([5, 7, 9])


In [43]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

result_sub_1 = torch.add(tensor_a, tensor_b)
result_sub_2 = tensor_a - tensor_b

print("func :",result_sub_1)
print("operation :", result_sub_2)

print(tensor_a.sub(tensor_b)) # But it doesnot effect the value of tensor_a
print(tensor_a)

print(tensor_a.sub_(tensor_b)) # It will effect the value of tensor_a
print(tensor_a)

func : tensor([5, 7, 9])
operation : tensor([-3, -3, -3])
tensor([-3, -3, -3])
tensor([1, 2, 3])
tensor([-3, -3, -3])
tensor([-3, -3, -3])


In [44]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

result_mul_1 = torch.add(tensor_a, tensor_b)
result_mul_2 = tensor_a * tensor_b

print("func :",result_sub_1)
print("operation :", result_sub_2)

print(tensor_a.mul(tensor_b)) # But it doesnot effect the value of tensor_a
print(tensor_a)

print(tensor_a.mul_(tensor_b)) # It will effect the value of tensor_a
print(tensor_a)

func : tensor([5, 7, 9])
operation : tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([1, 2, 3])
tensor([ 4, 10, 18])
tensor([ 4, 10, 18])


In [52]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

result_div_1 = torch.div(tensor_a, tensor_b)
result_div_2 = tensor_a / tensor_b

print("func :",result_sub_1)
print("operation :", result_sub_2)

print(tensor_a.div(tensor_b)) # But it doesnot effect the value of tensor_a
print(tensor_a)

print(tensor_a.float().div_(tensor_b.float())) # It will effect the value of tensor_a
print(tensor_a)

func : tensor([5, 7, 9])
operation : tensor([-3, -3, -3])
tensor([0.2500, 0.4000, 0.5000])
tensor([1, 2, 3])
tensor([0.2500, 0.4000, 0.5000])
tensor([1, 2, 3])


In [53]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

result_rem_1 = torch.remainder(tensor_a, tensor_b)
result_rem_2 = tensor_a % tensor_b

print("func :",result_sub_1)
print("operation :", result_sub_2)

print(tensor_a.remainder(tensor_b)) # But it doesnot effect the value of tensor_a
print(tensor_a)

print(tensor_a.float().remainder_(tensor_b.float())) # It will effect the value of tensor_a
print(tensor_a)

func : tensor([5, 7, 9])
operation : tensor([-3, -3, -3])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1., 2., 3.])
tensor([1, 2, 3])
