<a href="https://colab.research.google.com/github/NeuralDataMind/PyTorch/blob/main/Intro_to_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import torch
import numpy as np

In [51]:
tensor_1 = torch.tensor([1, 2, 3])
print("Our first PyTorch Tensor:", tensor_1)

Our first PyTorch Tensor: tensor([1, 2, 3])


In [52]:
array_1 = np.array([1, 2, 3])

In [53]:
tensor_from_numpy = torch.tensor(array_1)
print("PyTorch Twnsor from numpy arraay:", tensor_from_numpy)

PyTorch Twnsor from numpy arraay: tensor([1, 2, 3])


In [54]:
empty_tensor = torch.empty(3)
print("Empty Tensor:", empty_tensor)

Empty Tensor: tensor([0.0000e+00, 0.0000e+00, 7.7052e+31])


In [55]:
zero_tensor = torch.zeros(2, 3)
print("Zero Tensor:", zero_tensor)

Zero Tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [56]:
ones_tensor = torch.ones(2, 3)
print("Ones Tensor:", ones_tensor)

Ones Tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [57]:
ones_tensor.dtype # default it is float32

torch.float32

In [58]:
arange_tensor =torch.arange(start = 0, end = 10, step = 1)
print("Arange Tensor:", arange_tensor)

Arange Tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [59]:
random_tensor = torch.randn(3, 3)
print("Random Tensor:", random_tensor)

Random Tensor: tensor([[-0.1168,  0.3355, -0.5245],
        [ 2.4747, -0.1626, -1.0868],
        [-1.2025,  0.9806,  0.6411]])


In [60]:
random_tensor[0, 0]

tensor(-0.1168)

In [61]:
random_tensor[0, :]

tensor([-0.1168,  0.3355, -0.5245])

In [62]:
random_tensor[:, 0]

tensor([-0.1168,  2.4747, -1.2025])

In [63]:
random_tensor[1, 1].item()

-0.16258735954761505

In [64]:
reshaped_tensor = torch.rand(5, 4)
print("Reshaped Tensor", reshaped_tensor)

Reshaped Tensor tensor([[0.5283, 0.3118, 0.6703, 0.7234],
        [0.2837, 0.1823, 0.2073, 0.1675],
        [0.5706, 0.7241, 0.1816, 0.6787],
        [0.1356, 0.4107, 0.4315, 0.7233],
        [0.0207, 0.1934, 0.8572, 0.8731]])


**Reshape and view**

reshape and view both do same thing

In [65]:
new_reshaped_tensor = reshaped_tensor.view(4,5)
print("New Reshaped Tensor:", new_reshaped_tensor)

New Reshaped Tensor: tensor([[0.5283, 0.3118, 0.6703, 0.7234, 0.2837],
        [0.1823, 0.2073, 0.1675, 0.5706, 0.7241],
        [0.1816, 0.6787, 0.1356, 0.4107, 0.4315],
        [0.7233, 0.0207, 0.1934, 0.8572, 0.8731]])


In [66]:
new_reshaped_tensor = reshaped_tensor.view(-1, 2)
print("New Reshaped Tensor:", new_reshaped_tensor)

New Reshaped Tensor: tensor([[0.5283, 0.3118],
        [0.6703, 0.7234],
        [0.2837, 0.1823],
        [0.2073, 0.1675],
        [0.5706, 0.7241],
        [0.1816, 0.6787],
        [0.1356, 0.4107],
        [0.4315, 0.7233],
        [0.0207, 0.1934],
        [0.8572, 0.8731]])


In [67]:
new_reshaped_tensor = reshaped_tensor.view(5, -1)
print("New Reshaped Tensor:", new_reshaped_tensor)

New Reshaped Tensor: tensor([[0.5283, 0.3118, 0.6703, 0.7234],
        [0.2837, 0.1823, 0.2073, 0.1675],
        [0.5706, 0.7241, 0.1816, 0.6787],
        [0.1356, 0.4107, 0.4315, 0.7233],
        [0.0207, 0.1934, 0.8572, 0.8731]])


In [68]:
new_reshaped_tensor = reshaped_tensor.reshape(-1, 2)
print("New Reshaped Tensor:", new_reshaped_tensor)

New Reshaped Tensor: tensor([[0.5283, 0.3118],
        [0.6703, 0.7234],
        [0.2837, 0.1823],
        [0.2073, 0.1675],
        [0.5706, 0.7241],
        [0.1816, 0.6787],
        [0.1356, 0.4107],
        [0.4315, 0.7233],
        [0.0207, 0.1934],
        [0.8572, 0.8731]])


**Tensor Operations**

In [69]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

result_add_1 = torch.add(tensor_a, tensor_b)
result_add_2 = tensor_a + tensor_b

print("func :",result_add_1)
print("operation :", result_add_2)

func : tensor([5, 7, 9])
operation : tensor([5, 7, 9])


In [70]:
print(tensor_a.add(tensor_b)) # But it doesnot effect the value of tensor_a
print(tensor_a)

tensor([5, 7, 9])
tensor([1, 2, 3])


In [71]:
print(tensor_a.add_(tensor_b)) # It will effect the value of tensor_a
print(tensor_a)

tensor([5, 7, 9])
tensor([5, 7, 9])


In [72]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

result_sub_1 = torch.add(tensor_a, tensor_b)
result_sub_2 = tensor_a - tensor_b

print("func :",result_sub_1)
print("operation :", result_sub_2)

print(tensor_a.sub(tensor_b)) # But it doesnot effect the value of tensor_a
print(tensor_a)

print(tensor_a.sub_(tensor_b)) # It will effect the value of tensor_a
print(tensor_a)

func : tensor([5, 7, 9])
operation : tensor([-3, -3, -3])
tensor([-3, -3, -3])
tensor([1, 2, 3])
tensor([-3, -3, -3])
tensor([-3, -3, -3])


In [73]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

result_mul_1 = torch.add(tensor_a, tensor_b)
result_mul_2 = tensor_a * tensor_b

print("func :",result_sub_1)
print("operation :", result_sub_2)

print(tensor_a.mul(tensor_b)) # But it doesnot effect the value of tensor_a
print(tensor_a)

print(tensor_a.mul_(tensor_b)) # It will effect the value of tensor_a
print(tensor_a)

func : tensor([5, 7, 9])
operation : tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([1, 2, 3])
tensor([ 4, 10, 18])
tensor([ 4, 10, 18])


In [74]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

result_div_1 = torch.div(tensor_a, tensor_b)
result_div_2 = tensor_a / tensor_b

print("func :",result_sub_1)
print("operation :", result_sub_2)

print(tensor_a.div(tensor_b)) # But it doesnot effect the value of tensor_a
print(tensor_a)

print(tensor_a.float().div_(tensor_b.float())) # It will effect the value of tensor_a
print(tensor_a)

func : tensor([5, 7, 9])
operation : tensor([-3, -3, -3])
tensor([0.2500, 0.4000, 0.5000])
tensor([1, 2, 3])
tensor([0.2500, 0.4000, 0.5000])
tensor([1, 2, 3])


In [75]:
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])

result_rem_1 = torch.remainder(tensor_a, tensor_b)
result_rem_2 = tensor_a % tensor_b

print("func :",result_sub_1)
print("operation :", result_sub_2)

print(tensor_a.remainder(tensor_b)) # But it doesnot effect the value of tensor_a
print(tensor_a)

print(tensor_a.float().remainder_(tensor_b.float())) # It will effect the value of tensor_a
print(tensor_a)

func : tensor([5, 7, 9])
operation : tensor([-3, -3, -3])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1., 2., 3.])
tensor([1, 2, 3])


In [76]:
matrix_a = torch.tensor([[1, 2], [3, 4]])
matrix_b = torch.tensor([[2, 1], [4, 3]])

In [77]:
print("Matrix Add:\n", torch.add(matrix_a, matrix_b))
print("Matrix Sub:\n", torch.sub(matrix_a, matrix_b))
print("Matrix Mul:\n", torch.mm(matrix_a, matrix_b))
print("Matrix Div:\n", torch.div(matrix_a, matrix_b))
print("Matrix Rem:\n", torch.remainder(matrix_a, matrix_b))

Matrix Add:
 tensor([[3, 3],
        [7, 7]])
Matrix Sub:
 tensor([[-1,  1],
        [-1,  1]])
Matrix Mul:
 tensor([[10,  7],
        [22, 15]])
Matrix Div:
 tensor([[0.5000, 2.0000],
        [0.7500, 1.3333]])
Matrix Rem:
 tensor([[1, 0],
        [3, 1]])


**dtype**

In [78]:
matrix_a.dtype

torch.int64

In [79]:
a_tensor = torch.tensor([1, 2, 3], dtype=torch.float16) # default is float32
print("A Tensor:", a_tensor)
print(a_tensor.dtype)

A Tensor: tensor([1., 2., 3.], dtype=torch.float16)
torch.float16


In [80]:
tensor_int = torch.tensor([4, 5, 6], dtype=torch.int64)
print("tensor_int", tensor_int)
print(tensor_int.dtype)

tensor_int tensor([4, 5, 6])
torch.int64


In [81]:
tensor_float = tensor_int.to(torch.float32)
print(tensor_float)
print(tensor_float.dtype)

tensor([4., 5., 6.])
torch.float32


**Device**

In [82]:
tensor_float.device

device(type='cpu')

In [83]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [84]:
tensor_float.to(device)

tensor([4., 5., 6.], device='cuda:0')

In [85]:
torch.cuda.device_count()

1

In [86]:
torch.cpu.device_count()

1

In [88]:
tensor_new = torch.tensor([51.50, 46.2], dtype=torch.float32, device='cuda')

In [89]:
tensor_new.shape

torch.Size([2])