<a href="https://colab.research.google.com/github/NeuralDataMind/PyTorch/blob/main/softmax_and_CrossEntropy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Mannual Way**

In [1]:
import torch
import torch.nn as nn

In [2]:
logits = torch.tensor([[2.5, 0.2, 0.6], [0.3, 2.7, 0.3], [0.1, 0.2, 1.6]])
target = torch.tensor([0, 1, 2])

In [3]:
softmax_prob = torch.softmax(logits, dim = 1)

In [4]:
print(softmax_prob)

tensor([[0.8001, 0.0802, 0.1197],
        [0.0768, 0.8464, 0.0768],
        [0.1518, 0.1678, 0.6804]])


In [6]:
mannual_loss = torch.mean(-torch.log(softmax_prob.gather(1, target.view(-1, 1))))
print(mannual_loss.item())

0.25827091932296753


**Easy Way**

In [7]:
criterion = nn.CrossEntropyLoss()

In [9]:
loss = criterion(logits, target)
print(loss.item())

0.25827088952064514


*Example 2*

In [10]:
logits2 = torch.randn(5, 10)
target2 = torch.LongTensor([1, 7, 2, 4, 3])

In [11]:
logits2

tensor([[-0.7150, -0.1998,  0.3618,  0.3063,  1.0234, -1.6637,  0.5227, -0.1150,
          0.3419,  0.0110],
        [-1.4972, -1.3784, -0.0763, -0.7753,  0.4330,  2.5212,  0.9603,  1.4725,
         -0.2770,  2.1748],
        [ 0.0053, -1.2020,  0.7819, -1.9125,  0.6910, -0.6415, -0.0902, -0.6226,
          0.9771, -1.2169],
        [ 1.5422,  0.8596, -0.2087,  0.9632, -0.0258, -0.2422,  0.2794, -0.6693,
          0.2538, -0.6246],
        [ 0.8400,  1.2281,  0.2789,  0.2612,  0.4841, -0.7152,  0.9997,  0.1520,
         -1.3046, -0.1845]])

In [12]:
target2

tensor([1, 7, 2, 4, 3])

In [13]:
loss2 = criterion(logits2, target2)
print(loss2.item())

2.307736873626709
